server:
  port: 8080
spring:
  datasource:
    username: oytunuysal
    password: Sifre123*
    url: jdbc:mysql://oytunmysql.mysql.database.azure.com
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true